site_name: Django Paddle Subscriptions
site_url: https://websightful.github.io/django-paddle-subscriptions-docs/
site_description: Django Paddle Subscriptions Documentation
site_author: Aidas Bendoraitis a.k.a. archatas / DjangoTricks
docs_dir: src
site_dir: docs
repo_url: https://websightful.gumroad.com/l/django-paddle-subscriptions
repo_name: Buy Now!
extra_css:
  - css/style.css

nav:
    - Home: 'index.md'
    - Screenshots: 'screenshots.md'
    - Getting Started: 'getting-started.md'
    - 'More':
        - Customization: 'customization.md'
        - Troubleshooting: 'troubleshooting.md'
        - Changelog: 'CHANGELOG.md'
        - License: 'LICENSE.md'